### ISSUE TITLE
Mudate a React XDDDD

### ISSUE THREAD

**Issue by syntaxbliss** [komalakd/angular_velocity#1]
a la breve sale angular2, y ahi ES6 va a romper todo, asi q espera a que salga angular2 o mudate a react jijiji saludos comadrejilla! :D

paajaritooh ree turro :S

PD: quise mandar un mensaje personal pero guitjab no provee esa funcionalidad, una pija...

**Comment by valleandres** [comment]
Aguante el backend lpm!!!
